---
name: Deploy - DEV

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]
  workflow_dispatch:

concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    name: Deploy to Vercel
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # ---------- publish ----------
      - name: Install Vercel CLI
        run: npm install --global vercel@canary
      # ---------- ENV: production ----------
      - name: Deploy to Vercel
        if: github.event_name == 'push'
        run: |
          export VERCEL_ORG_ID=${{ secrets.VERCEL_ORG_ID }}
          export VERCEL_PROJECT_ID=${{ secrets.VERCEL_PROJECT_ID_DEV }} # BRANCH-SPECIFIC
          export VERCEL_TOKEN=${{ secrets.VERCEL_TOKEN }}

          vercel pull --yes --environment=production --token="$VERCEL_TOKEN"
          vercel build --prod --token="$VERCEL_TOKEN"
          vercel deploy --prebuilt --prod --token="$VERCEL_TOKEN"
      # ---------- ENV: production - preview ----------
      - name: Deploy to Vercel - PREVIEW
        id: deploy-preview
        if: github.event_name == 'pull_request'
        run: |
          export VERCEL_ORG_ID=${{ secrets.VERCEL_ORG_ID }}
          export VERCEL_PROJECT_ID=${{ secrets.VERCEL_PROJECT_ID_DEV }} # BRANCH-SPECIFIC
          export VERCEL_TOKEN=${{ secrets.VERCEL_TOKEN }}

          vercel pull --yes --environment=preview --token="$VERCEL_TOKEN"
          vercel build --token="$VERCEL_TOKEN"
          vercel deploy --prebuilt --token="$VERCEL_TOKEN" 2>&1 | tee output.txt
      # ---------- display preview link ----------
      - name: Add preview url to pr comment
        if: github.event_name == 'pull_request'
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: output.txt
